import { useEffect, useState } from "react";
import { RecommendationItem } from "../types";
import { getRecommendations } from "../services/movieApi";
import { useAuth } from "../context/AuthContext";

const RecommendationsPage = () => {
  const { token } = useAuth();
  const [recommendations, setRecommendations] = useState<RecommendationItem[]>(
    [],
  );
  const [source, setSource] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!token) return;

    setLoading(true);
    setError(null);
    getRecommendations()
      .then((data) => {
        const items: RecommendationItem[] = data?.recommendations || data || [];
        setSource(data?.source || null);
        setRecommendations(items);
      })
      .catch((err: any) => {
        console.error(err);
        const serverMessage = err?.response?.data?.message;
        setError(
          serverMessage ||
            "Unable to load recommendations. Rate at least 3 watched movies and try again.",
        );
      })
      .finally(() => setLoading(false));
  }, [token]);

  return (
    <div className="relative mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Background decoration glows */}
      <div className="absolute top-10 right-10 w-96 h-96 bg-accent-purple/5 blur-[120px] rounded-full pointer-events-none" />
      <div className="absolute top-1/2 left-10 w-80 h-80 bg-accent/5 blur-[120px] rounded-full pointer-events-none" />

      {/* Header Deck */}
      <div className="relative z-10 rounded-3xl border border-slate-800 bg-surface/50 p-8 backdrop-blur-md shadow-xl shadow-black/25">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <h1 className="text-4xl font-extrabold text-white sm:text-5xl tracking-tight">
              AI Recommendations
            </h1>
            <p className="mt-3 max-w-2xl text-slate-400 sm:text-base leading-relaxed">
              Personalized cinema suggestions generated by Gemini, tailored specifically to your rating history.
            </p>
          </div>
          {source && (
            <span className={`inline-flex rounded-xl px-4.5 py-2 text-xs font-bold uppercase tracking-widest border border-slate-800 ${
              source === "ai"
                ? "bg-rose-500/10 text-rose-400 border-rose-500/20"
                : "bg-slate-900 text-slate-300"
            }`}>
              Source: {source}
            </span>
          )}
        </div>
      </div>

      {loading ? (
        /* Premium Loading Skeleton */
        <div className="mt-8 grid gap-6 lg:grid-cols-2 relative z-10">
          {[1, 2, 4, 5].map((i) => (
            <div key={i} className="rounded-3xl border border-slate-900 bg-surface/40 p-6 shadow-md animate-pulse">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 space-y-3">
                  <div className="h-6 w-1/2 rounded bg-slate-800" />
                  <div className="h-4 w-3/4 rounded bg-slate-800" />
                  <div className="h-4 w-5/6 rounded bg-slate-800" />
                </div>
                <div className="h-10 w-12 rounded-xl bg-slate-800" />
              </div>
            </div>
          ))}
        </div>
      ) : error ? (
        <div className="mt-8 rounded-3xl border border-red-900/50 bg-red-950/20 p-6 text-slate-200 shadow-lg relative z-10 flex items-center gap-3">
          <svg className="h-5 w-5 text-red-400 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <div className="text-sm font-medium">{error}</div>
        </div>
      ) : (
        <div className="mt-8 grid gap-6 lg:grid-cols-2 relative z-10">
          {recommendations.length ? (
            recommendations.map((item, index) => {
              const title = item.title || `Recommendation ${index + 1}`;
              const reason =
                item.reason ||
                "This movie matches your interest and director/genre profile.";
              const confidence = Number(item.confidence) || 72;

              // Color coordinate rating confidence
              const confidenceBadgeStyle = (val: number) => {
                if (val >= 90) return "bg-accent-gold/10 text-accent-gold border-accent-gold/20";
                if (val >= 80) return "bg-accent-purple/10 text-accent-purple border-accent-purple/20";
                return "bg-accent/10 text-accent border-accent/20";
              };

              return (
                <div
                  key={`${title}-${confidence}-${index}`}
                  className="group rounded-3xl border border-slate-900 bg-surface p-5 shadow-xl transition-all duration-300 hover:-translate-y-1.5 hover:border-slate-800 hover:shadow-2xl flex flex-col sm:flex-row gap-5"
                >
                  {item.posterPath && (
                    <div className="w-24 sm:w-28 shrink-0 overflow-hidden rounded-xl border border-slate-800 bg-slate-950 shadow-md aspect-[2/3]">
                      <img
                        className="h-full w-full object-cover transition duration-300 group-hover:scale-105"
                        src={`https://image.tmdb.org/t/p/w500${item.posterPath}`}
                        alt={title}
                        loading="lazy"
                      />
                    </div>
                  )}
                  <div className="flex flex-col justify-between flex-1">
                    <div>
                      <div className="flex items-start justify-between gap-4">
                        <h2 className="text-xl font-bold text-slate-200 group-hover:text-accent transition duration-200 line-clamp-1">
                          {title}
                        </h2>
                        <span className={`shrink-0 rounded-xl border px-2.5 py-1.5 text-xs font-bold ${confidenceBadgeStyle(confidence)}`}>
                          {confidence}% Match
                        </span>
                      </div>
                      <p className="mt-3 text-sm text-slate-400 leading-relaxed line-clamp-3 sm:line-clamp-4">{reason}</p>
                    </div>
                  </div>
                </div>
              );
            })
          ) : (
            <div className="col-span-2 rounded-3xl border border-slate-900 bg-surface/50 p-10 text-center shadow-lg">
              <h2 className="text-xl font-bold text-white">
                No recommendations yet
              </h2>
              <p className="mt-3 text-sm text-slate-400 max-w-md mx-auto leading-relaxed">
                Rate at least 3 movies from your watched list to unlock personalized AI-driven movie recommendations.
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default RecommendationsPage;
